### ISSUE TITLE
flair.css not present for all styles

### ISSUE THREAD

**Issue by berlincount** [stevotvr/phpbb-flair#2]
```
[27-Feb-2018 15:04:12 Europe/Berlin] PHP Fatal error:  Uncaught Twig_Error_Loader: Unable to find template "@stevotvr_flair/flair.css" (looked into: ext/stevotvr/flair/styles/all/template, ext/stevotvr/flair/styles/all/template) in "@stevotvr_flair/event/overall_header_head_append.html" at line 5. in vendor/twig/twig/lib/Twig/Loader/Filesystem.php:232
Stack trace:
#0 phpbb/template/twig/loader.php(135): Twig_Loader_Filesystem->findTemplate('@stevotvr_flair...')
#1 vendor/twig/twig/lib/Twig/Loader/Filesystem.php(150): phpbb\template\twig\loader->findTemplate('@stevotvr_flair...')
#2 phpbb/template/twig/environment.php(328): Twig_Loader_Filesystem->getCacheKey('@stevotvr_flair...')
#3 vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 232
```

ouch ;)

```
mkdir ext/stevotvr/flair/styles/all/theme
cp ext/stevotvr/flair/styles/prosilver/theme/flair.css ext/stevotvr/flair/styles/all/theme
```

was the quickfix.

**Comment by stevotvr** [comment]
That's intentional. The CSS may not be compatible with all custom styles. So if you have a custom style, you'll need to copy the file and make any necessary adjustments.

**Comment by berlincount** [comment]
Consider shipping an empty `flair.css`, so it fails somewhat softer, please :)

Wasn't even able to get into the admin anymore ...

**Comment by stevotvr** [comment]
Yeah, I guess that would be better.
